### ISSUE TITLE
NAMESPACE variable not being substituted 

### ISSUE THREAD

**Issue by ankurcha** [adobe/rules_gitops#117]
### Description of the problem / feature request:

I am new user of the adobe/rules_gitops rules and noticed something that doesn't seem to match docs and wanted to check of I am doing something wrong

I have a manifest that looks like this:

```
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{NAME}}-reader-binding"
subjects:
  - kind: ServiceAccount
    name: "{{NAMESPACE}}-vault"
    namespace: "{{NAMESPACE}}"
roleRef:
  kind: Role
  name: "{{NAME}}-reader"
  apiGroup: rbac.authorization.k8s.io
```

But after running `bazel build //...` the output in `bazel-bin/ `

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-reader-binding
  namespace: data-exposure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-reader
subjects:
- kind: ServiceAccount
  name: '{{NAMESPACE}}-vault'
  namespace: '{{NAMESPACE}}'
```
It looks like only the NAMESPACE variable is not being replaced.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Create a manifest with:

```
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{NAME}}-reader-binding"
subjects:
  - kind: ServiceAccount
    name: "{{NAMESPACE}}-vault"
    namespace: "{{NAMESPACE}}"
roleRef:
  kind: Role
  name: "{{NAME}}-reader"
  apiGroup: rbac.authorization.k8s.io
```

And then create a k8s_deploy with `substituions = {"NAME": "app"}` 

### What operating system are you running Bazel on?

Ubuntu 20

### What's the output of `bazel info release`?

```
❯ bazel info release
INFO: Invocation ID: e09fcfdd-4c8b-4ddd-b46e-d066e7077769
release 5.3.2
```

### Snippet of the `WORKSPACE` file that includes rules_gitops rules.

```
git_repository(
        name = "com_adobe_rules_gitops",
        remote = "git@github.com:adobe/rules_gitops.git",
        commit = "cf3e17c51253516f3ab674925532f638796822a3",
    )
```

###  Have you found anything relevant by searching the web?

No

### Any other information, logs, or outputs that you want to share?

> Replace these lines with your answer.
>
> If the files are large, upload as attachment or provide link.
